### ISSUE TITLE
Vastly different exceptions thrown for different errors on connect

### ISSUE THREAD

**Issue by philip-stoev** [nuodb/nuodb-python#10]
For different errors in connect(), vastly different exceptions are thrown. I think it may be better to standardize them somehow so that they can all be handled uniformly:

- wrong database - SessionException
- wrong host - gaierror: [Errno -2] Name or service not known
- wrong password -  SessionException: 'Session was closed while receiving'
- wrong user - ProgrammingError: 'SECURITY_ERROR: "nosuchuser" is not a known user for database "test"'

**Comment by tvincentNuoDB** [comment]
These look to be resolved, for example wrong database now yields:
`pynuodb.session.SessionException: 'No such database: wrongDatabase'`
