### ISSUE TITLE
Latest py.pi release has .REL extension

### ISSUE THREAD

**Issue by rbuck** [nuodb/nuodb-python#110]
To declare a dependency I have to add -REL rather than just use the version number:

-pynuodb>=2.3
+pynuodb>=2.3-REL

This regards the files posted on py.pi:
pynuodb-2.3-REL.tar.gz (md5)
When the file name ought to have been:
pynuodb-2.3.tar.gz (md5)

**Comment by tvincentNuoDB** [comment]
Hi Bob,

This was my mistake. I originally uploaded pynuodb-2.3.tar.gz but, having changed that link you found, had to change the file name as pypi doesn't allow the same file name twice

**Comment by rbuck** [comment]
Can you delete the whole release and start fresh so that you can push an
update?

On Mon, Jun 29, 2015 at 2:57 PM, Tim Vincent <notifications@github.com>
wrote:

> Hi Bob,
>
> This was my mistake. I originally uploaded pynuodb-2.3.tar.gz but, having
> changed that link you found, had to change the file name as pypi doesn't
> allow the same file name twice
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nuodb/nuodb-python/issues/110#issuecomment-116796324>.
>



-- 
Robert Buck
Principal Solutions Architect
*www.nuodb.com* <http://www.nuodb.com/>
c: 508-603-9435
t: @nuodb <https://twitter.com/nuodb>
f: *facebook.com/NUODB <https://www.facebook.com/NUODB>*
skype: buck.robert.j

The information contained in this email is confidential and proprietary and
intended for the sole use of the intended recipient. If the reader of this
message is not the intended recipient, you are hereby notified that any
dissemination, distribution or copying of this communication is strictly
prohibited. If you have received this email in error, please notify the
sender and delete all copies.
