### ISSUE TITLE
putScaledCount2 uses toSignedByteString and sends the sign as a string

### ISSUE THREAD

**Issue by gittywithexcitement** [nuodb/nuodb-python#112]
`putScaledCount2` encodes `value` with `toSignedByteString` as well as sending the sign as the string "1" or "-1". This seems redundant. Why send "1" or "-1" when `toSignedByteString` is used?

**Comment by gittywithexcitement** [comment]
I also noticed that `getScaledCount2` is inconsistent with `putScaledCount2`.

* `getScaledCount2` expects sign to be one byte, decoded by `fromSignedByteString`, with a value less than zero indicating a negative number.
* `putScaledCount2` encodes the sign as one or two bytes, using ASCII encoding of "1" or "-1"

and

* `getScaledCount2` decodes the value with `fromByteString`
* `putScaledCount2` encodes the value with `toSignedByteString` (key difference being 'Signed')

I suspect that `getScaledCount2` is correct, and `putScaledCount2` is wrong. If `putScaledCount2` did the inverse of `getScaledCount2`, then the inconsistencies I mentioned above would disappear.

**Comment by tvincentNuoDB** [comment]
This is a flaw I have addressed in [PR](https://github.com/nuodb/nuodb-python/pull/113). The sign is now encoded as a bytes string, as well the absolute value of the ScaledCount2 is taken and encoded using  `toByteString` as the sign will no longer be present.
