### ISSUE TITLE
[Question] Is there a way to get column names along with a query?

### ISSUE THREAD

**Issue by joeycozza** [nuodb/nuodb-python#126]
When I execute a SELECT statement, I do get the rows back like I expected, but I was also wanting to see the names of the columns in the response.  

Here is my code I'm testing with
```python
import pynuodb
options = {'schema': "MY_SCHEMA"}
connect_kw_args = {'database': "MY_DB", 'host': "MY_HOST", 'user': "MY_USER", 'password': "MY_PW", 'options': options}
connection = pynuodb.connect(**connect_kw_args)
cursor = connection.cursor()
stmt_select = "SELECT * FROM Money LIMIT 2"
cursor.execute(stmt_select)
print("Results:")
for row in cursor.fetchall():
    print(row)
cursor.close()
connection.close()
```

OUTPUT:  
```
Results:
(1, 'USD', '155.48')
(2, 'USD', '149.99')
```

DESIRED OUTPUT: (something like this)
```
Results:
('Id', 'Denomination', 'Value')
(1, 'USD', '155.48')
(2, 'USD', '149.99')
```

Is there any way to get something like that?  Thanks for the help.

**Comment by sethtp** [comment]
I believe that the 'description' field on the cursor is what you want. It's an array with information about each column. In your example, 'len(cursor.description)' is 3 and 'cursor.description[0][0]' is 'Id'. I may be working off an older spec but I'd give that a try.

**Comment by joeycozza** [comment]
That worked great. Thanks so much.
