### ISSUE TITLE
Add ability to suspend enforcement on a host to entity code.

### ISSUE THREAD

**Issue by adriansuarez** [nuodb/nuodb-python#61]
This is a new feature in 2.2 that allows a host to be put into maintenance mode so that the enforcer doesn't try to start processes on it. We have yet to add python support for it.

**Comment by madscientist** [comment]
We won't be adding support for the NuoDB Admin management to the pynuodb driver, and we won't be improving support for the deprecated NuoDB Agent support currently in pynuodb.

For managing NuoDB Admin, please use the pynuoadmin facility provided with the NuoDB database (and available separately in the nuodb/nuodb-client package).
