### ISSUE TITLE
README should link to PEP 249

### ISSUE THREAD

**Issue by madscientist** [nuodb/nuodb-python#68]
The README is very minimal: it should specify that nuodb-python intends to comply with PEP 249 and provide a link to it, so users can get more details easily.

**Comment by tvincentNuoDB** [comment]
I'll get right on adding this to the README

**Comment by tvincentNuoDB** [comment]
Whoops, forgot to update this issue when I pushed the [change](https://github.com/tvincentNuoDB/nuodb-python/commit/70575b6500a6b9c33531d0fb222745e43a399ab2).

**Comment by madscientist** [comment]
Somehow this disappeared.  There's currently nothing whatsoever in the README that helps people understand how to use the package, except for a few trivial getting-started examples.

**Comment by rbuck** [comment]
Fixed.
