### ISSUE TITLE
Please use common syntax for 2.7.x and 3.4.x

### ISSUE THREAD

**Issue by rbuck** [nuodb/nuodb-python#72]
When rewriting or fixing this driver, please use syntax supported by more than one virtual of Python; using virtualenv to support testing assert the driver installs for both 3.4.3 and 2.7.6 without issue and tests satisfactorily.

Thank you.

**Comment by mjmichaels** [comment]
My understanding is that our current driver supports Python 2.7 only.

**Comment by rbuck** [comment]
Yes, and it's a few lines of code that get in the way. Basic things like,
add parens to print statements, replace unicode(str) with u'str', etc. It's
a few little things, should take one 30 mins to fix it at most.

I just did this on the SQLAlchemy side in less than 10 mins -- it's very
easy to do.

Bob

On Fri, May 22, 2015 at 8:15 AM, mjmichaels <notifications@github.com>
wrote:

> My understanding is that our current driver supports Python 2.7 only.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nuodb/nuodb-python/issues/72#issuecomment-104646293>.
>



-- 
Robert Buck
Principal Solutions Architect
*www.nuodb.com* <http://www.nuodb.com/>
c: 508-603-9435
t: @nuodb <https://twitter.com/nuodb>
f: *facebook.com/NUODB <https://www.facebook.com/NUODB>*
skype: buck.robert.j

The information contained in this email is confidential and proprietary and
intended for the sole use of the intended recipient. If the reader of this
message is not the intended recipient, you are hereby notified that any
dissemination, distribution or copying of this communication is strictly
prohibited. If you have received this email in error, please notify the
sender and delete all copies.

**Comment by tvincentNuoDB** [comment]
I think this switch may be a little less superficial than we originally thought, there are some core features to the driver such as StandardError which do not have support in 3.0+

**Comment by rbuck** [comment]
Both 2.x and 3.x support Exception. Fairly painless.

**Comment by rbuck** [comment]
To help you get going a little bit... Here are some things that the MySQL community did:

First, they derive the exceptions, not from StandardException, but from Exception (or Error as the case may be):

    https://github.com/PyMySQL/PyMySQL/blob/master/pymysql/err.py

They also tend to have a compatibility layer to accommodate both versions:

    https://github.com/PyMySQL/PyMySQL/blob/master/pymysql/_compat.py
    https://github.com/PyMySQL/mysqlclient-python/blob/master/MySQLdb/compat.py

I think these are reasonable choices given that we have customers that mandate python 2.76 and others that use 3.x.

Other examples, similar for Postgres:

    https://github.com/psycopg/psycopg2/blob/master/psycopg/connection_type.c

And for IBM DB2, similar choices:

    https://code.google.com/p/ibm-db/source/browse/IBM_DB/ibm_db/ibm_db_dbi.py

**Comment by rbuck** [comment]
And for an example, here is a port to 3.4 that is very nearly complete:

https://github.com/rbuck/nuodb-python/commit/c31cd42a57ae955167726b69b34c1c49bf839d3e

-Bob

**Comment by rbuck** [comment]
Tim, the technique I used to do this was to have two parallel virtual environments, then run `python setup.py install` from both, then simply slug through each error, looking at the Python migrators guide for 2.7.6 to 3.4 as a guide, and occasionally Google is your friend. It's pretty straight forward.

**Comment by rbuck** [comment]
Many of the changes I made here are per PEP 328, a spec written 12 years ago on how to properly use import in Python that was incorporated as of Python 2.5. I can create a pull request for this if you want.

**Comment by tvincentNuoDB** [comment]
Thanks Bob, I was able to update the exception handling yesterday, although I am still ironing out some bugs such as [this](https://github.com/nuodb/nuodb-python/blame/ec93c959225343de581b96e0dca422c3f0fc734e/tests/dbapi20.py#L189-197) with test cases. If you want to make a pull request updating the import statements that would be great!

**Comment by rbuck** [comment]
Hi Tim, there are a bunch of unrelated fixes in there. Let me stage them in. Here are some things I saw:

- relative imports
- pipy site complains about README.md, ought to be README.rst to work with pipy properly.
- setup.py missing depends declaration and setuptools is not configured properly
- misc code cleanups

I will break these down into separate pull requests. Please push your changes so I can merge and validate with yours in place so we don't conflict?

**Comment by tvincentNuoDB** [comment]
Sounds good! Okay I will stage mine and create a pull request as well. The README.rst is defiantly needed, as the README.md file does not display well on pipy.

**Comment by tvincentNuoDB** [comment]
Hey Bob, I'm going to close this since the driver now includes Python 3 syntax. It's just buttoning up handling Binary and byte types
