### ISSUE TITLE
Severe Bug: Protocol Mnemonic Redeclared

### ISSUE THREAD

**Issue by rbuck** [nuodb/nuodb-python#84]
The GENHTML mnemonic in protocol.py is declared differently in two places. I cannot see how this can possibly be a good thing.

**Comment by tvincentNuoDB** [comment]
Hmm interesting, could this be from the coverage test? Looking at the [Linux man page](http://linux.die.net/man/1/genhtml) it seems to be a method to generate reports from coverage testing.

**Comment by rbuck** [comment]
Static code analysis turned this up. Looking at the source code it seems it could be a problem. Could you investigate along with the unicode bugs.

**Comment by tvincentNuoDB** [comment]
Sure thing!

**Comment by tvincentNuoDB** [comment]
It looks like protocol 12 should actually be GenConnectionHtml and 29 is correct as GENHTML, still looking into this.

**Comment by tvincentNuoDB** [comment]
Okay, I made a [pull request](https://github.com/nuodb/nuodb-python/pull/85) to update the definition. It doesn't seem to be implemented yet so there was no change in testing
