### ISSUE TITLE
sending a scaled time as a unsigned byte string?

### ISSUE THREAD

**Issue by gittywithexcitement** [nuodb/nuodb-python#92]
Is sending a scaled time as a unsigned byte string correct?
https://github.com/nuodb/nuodb-python/blob/979c80d4674e0e5570ac38afce3dbd523548a5d1/pynuodb/encodedsession.py#L494

Let's assume the time we're trying to encode is 1 minute after midnight, local time; local time offset is negative 1 hour (perhaps we're in Western Europe).

[Here](https://github.com/nuodb/nuodb-python/blob/master/pynuodb/datatype.py#L80) we add the offset of the local timezone, which is negative (as described in the [python documentation](https://docs.python.org/2/library/time.html?highlight=timezone#time.timezone), offsets may be negative). So now our value is (-59 minutes * 60 seconds/minute) = -3540. Then we use `toByteString` to encode that negative value.

I have not tested any of this by hand, but this seems like a possible error to me.

The [dotnet driver](https://github.com/nuodb/nuodb-dotnet/blob/4f9e6e43c61e0450670707baaefc69f7b748e60c/NuoDb.Data.Client/EncodedDataStream.cs#L1641-L1644) encodes scaled time as a signed byte string, if I'm reading it correctly.

**Comment by tvincentNuoDB** [comment]
I've been doing some testing and this is indeed an issue. With a timezone shift of -1 at pynuodb.Time(0, 0, 0) I have found fault. This gives us a shift of -3600 and a total time of -36000, putting this through `toByteString` and back we get a value of 29536. This issue also lives in the `getScaledTime` as the time is taken out of `fromByteString`. I will fix these issues and make a PR
