### ISSUE TITLE
Incorrect test cases in large e notation test

### ISSUE THREAD

**Issue by tvincentNuoDB** [nuodb/nuodb-python#97]
We may want to revise the test cases in test_enotation_decimal_large. Values passed to the database are converted from e notation to decimal and passed back in decimal, despite this the assert statements are checking for the value in e notation, thus the test asserts. 

From testing, NuoSQL responds the same way as the driver with returning a decimal value.

**Comment by tvincentNuoDB** [comment]
[Here](https://github.com/nuodb/nuodb-python/blob/master/tests/nuodb_basic_test.py#L176-L188) is the test in question.

**Comment by rbuck** [comment]
So let's be careful on this one. The test is from sql alchemy. It works
with competitors databases. So let's s see what we can do to make it pass
as is.

**Comment by mjmichaels** [comment]
I don't know how we can get this correct. We're creating a Decimal object, inserting it into the database, retrieving it from the database, and somehow we have to remember that the python Decimal object that we inserted was in e-notation versus decimal notation? We don't store anything like this in the db. We have no way of knowing whether the value inserted into the db had been created with Decimal('123.45') versus Decimal('12345e-2').

**Comment by rbuck** [comment]
Do we know scale AND value, or do we just send a double?

On Mon, Jun 8, 2015 at 3:09 PM, mjmichaels <notifications@github.com> wrote:

> I don't know how we can get this correct. We're creating a Decimal object,
> inserting it into the database, retrieving it from the database, and
> somehow we have to remember that the python Decimal object that we inserted
> was in e-notation versus decimal notation? We don't store anything like
> this in the db. We have no way of knowing whether the value inserted into
> the db had been created with Decimal('123.45') versus Decimal('12345e-2').
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nuodb/nuodb-python/issues/97#issuecomment-110109987>.
>



-- 
Robert Buck
Principal Solutions Architect
*www.nuodb.com* <http://www.nuodb.com/>
c: 508-603-9435
t: @nuodb <https://twitter.com/nuodb>
f: *facebook.com/NUODB <https://www.facebook.com/NUODB>*
skype: buck.robert.j

The information contained in this email is confidential and proprietary and
intended for the sole use of the intended recipient. If the reader of this
message is not the intended recipient, you are hereby notified that any
dissemination, distribution or copying of this communication is strictly
prohibited. If you have received this email in error, please notify the
sender and delete all copies.

**Comment by mjmichaels** [comment]
We know scale and value. We don't know how it was originally specified, as e-notation or as a decimal value, which seems to be what this test wants. It seems to want that if the value was specified in e-notation it would be returned in e-notation.

**Comment by rbuck** [comment]
I think it will just work, IIRC.

On Mon, Jun 8, 2015 at 6:54 PM, mjmichaels <notifications@github.com> wrote:

> We know scale and value. We don't know how it was originally specified, as
> e-notation or as a decimal value, which seems to be what this test wants.
> It seems to want that if the value was specified in e-notation it would be
> returned in e-notation.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nuodb/nuodb-python/issues/97#issuecomment-110166173>.
>



-- 
Robert Buck
Principal Solutions Architect
*www.nuodb.com* <http://www.nuodb.com/>
c: 508-603-9435
t: @nuodb <https://twitter.com/nuodb>
f: *facebook.com/NUODB <https://www.facebook.com/NUODB>*
skype: buck.robert.j

The information contained in this email is confidential and proprietary and
intended for the sole use of the intended recipient. If the reader of this
message is not the intended recipient, you are hereby notified that any
dissemination, distribution or copying of this communication is strictly
prohibited. If you have received this email in error, please notify the
sender and delete all copies.

**Comment by mjmichaels** [comment]
I don't see how Bob, but Tim is going to do some testing. Python passes an e-notation string to the server. The TE parses it and creates a Value object with scale. That's all we know. After that there is no knowledge of what format the original string was in.

**Comment by tvincentNuoDB** [comment]
Hi Bob,

I'm not sure python converts values automatically into E notation. Here are some tests I did in 3.4 with the decimal class.
```Python
>>> decimal.Decimal("400000000")
Decimal('400000000')
```
```Python

>>> d = decimal.Decimal('4E+8')
>>> d + 1
Decimal('400000001')
```

**Comment by rbuck** [comment]
I would strongly recommend using PyCharm rather than the interactive
debugger at the CLI.

Here's a pic of what you have in Python; here you see scale and value, the
first two fields:

[image: Inline image 1]

If you get scale and value sent/recv correctly, it will all work correctly.

The proper way to construct a Decimal from scale and value are:

Decimal((0, (3, 1, 4), -2))  # tuple (sign, digit_tuple, exponent)

Please see my prior example/fix for an example, which is:

            sign = 1 if value < 0 else 0
            value = tuple(int(i) for i in str(abs(value)))
            return decimal.Decimal((sign, value, -1 * scale))

That is what will work.


On Tue, Jun 9, 2015 at 8:43 AM, Tim Vincent <notifications@github.com>
wrote:

> Hi Bob,
>
> I'm not sure python converts values automatically into E notation. Here
> are some tests I did in 3.4 with the decimal class.
>
> >>> decimal.Decimal("400000000")
> Decimal('400000000')
>
> >>> d = decimal.Decimal('4E+8')>>> d + 1
> Decimal('400000001')
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nuodb/nuodb-python/issues/97#issuecomment-110345081>.
>



-- 
Robert Buck
Principal Solutions Architect
*www.nuodb.com* <http://www.nuodb.com/>
c: 508-603-9435
t: @nuodb <https://twitter.com/nuodb>
f: *facebook.com/NUODB <https://www.facebook.com/NUODB>*
skype: buck.robert.j

The information contained in this email is confidential and proprietary and
intended for the sole use of the intended recipient. If the reader of this
message is not the intended recipient, you are hereby notified that any
dissemination, distribution or copying of this communication is strictly
prohibited. If you have received this email in error, please notify the
sender and delete all copies.

**Comment by tvincentNuoDB** [comment]
Hi Bob,

I've been playing around with some things regarding notation. A cheap trick I noticed that allows us to handle e-notation is setting value += 0 in putScaledInt, this way the value is sent in decimal notation.

As well I updated _test_decimal_fixture to match test_float_into_number which meant dropping the string literal assert. 

Not sure if you want me to push these changes? Still working on the invalid UTF-8 test case

**Comment by rbuck** [comment]
Just bear in mind that if you change the fixtures I created, you're
changing the test code from SQL Alchemy. So the test may become invalid
from that perspective.

On Tue, Jun 9, 2015 at 11:44 AM, Tim Vincent <notifications@github.com>
wrote:

> Hi Bob,
>
> I've been playing around with some things regarding notation. A cheap
> trick I noticed that allows us to handle e-notation is setting value += 0
> in putScaledInt, this way the value is sent in decimal notation.
>
> As well I updated _test_decimal_fixture to match test_float_into_number
> which meant dropping the string literal assert.
>
> Not sure if you want me to push these changes? Still working on the
> invalid UTF-8 test case
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nuodb/nuodb-python/issues/97#issuecomment-110408077>.
>



-- 
Robert Buck
Principal Solutions Architect
*www.nuodb.com* <http://www.nuodb.com/>
c: 508-603-9435
t: @nuodb <https://twitter.com/nuodb>
f: *facebook.com/NUODB <https://www.facebook.com/NUODB>*
skype: buck.robert.j

The information contained in this email is confidential and proprietary and
intended for the sole use of the intended recipient. If the reader of this
message is not the intended recipient, you are hereby notified that any
dissemination, distribution or copying of this communication is strictly
prohibited. If you have received this email in error, please notify the
sender and delete all copies.

**Comment by tvincentNuoDB** [comment]
That's true, although it's notation which it's failing on, not value.

One thing I noticed about the decimal class is that the scale must be greater than 1 for any conversion to scientific notation to occur. ('%g' % decimal) will format the data in this notation for testing but, is pretty useless since it's string formatting.

**Comment by tvincentNuoDB** [comment]
I was looking at the SQL Alchemy source code for the tests and noticed they have set a warning above the test we are failing    
```Python
@testing.emits_warning(r".*does \*not\* support Decimal objects natively")
```
Looking through their API, it seems they have created their own double class to handle decimals, I'm guessing this is the test is looking for

**Comment by rbuck** [comment]
That's a sentinel for databases that don't support Decimal natively. If we
support scale and precision then we support it. Each DB type can create
their own types, for those types that SQL does not itself expose, or for
those types that don't map in quite right.

I believe we can make this work cleanly within the Python driver layer
without any adaptation in SQL Alchemy.

Bob

On Wed, Jun 10, 2015 at 7:20 AM, Tim Vincent <notifications@github.com>
wrote:

> I was looking at the SQL Alchemy source code for the tests and noticed
> they have set a warning above the test we are failing
>
> @testing.emits_warning(r".*does \*not\* support Decimal objects natively")
>
> Looking through their API, it seems they have created their own double
> class to handle decimals, I'm guessing this is the test is looking for
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nuodb/nuodb-python/issues/97#issuecomment-110704916>.
>



-- 
Robert Buck
Principal Solutions Architect
*www.nuodb.com* <http://www.nuodb.com/>
c: 508-603-9435
t: @nuodb <https://twitter.com/nuodb>
f: *facebook.com/NUODB <https://www.facebook.com/NUODB>*
skype: buck.robert.j

The information contained in this email is confidential and proprietary and
intended for the sole use of the intended recipient. If the reader of this
message is not the intended recipient, you are hereby notified that any
dissemination, distribution or copying of this communication is strictly
prohibited. If you have received this email in error, please notify the
sender and delete all copies.

**Comment by tvincentNuoDB** [comment]
For now we will be using the standard decimal notation provided by Python's decimal class. It has been noted that the putScaledInt and getScaledInt do not hold E notation. Updated in PR [https://github.com/nuodb/nuodb-python/pull/96]
